package com.beckytidus.girlfriendmod.registry;

import net.minecraft.util.RandomSource;

import java.util.List;

public final class FemaleNames {
    private static final List<String> NAMES = List.of(
        "Abigail", "Ada", "Adelaide", "Adeline", "Aria", "Alice", "Amelia", "Anastasia", "Angela", "Anna",
        "Annabelle", "Ariana", "Ashley", "Audrey", "Aurora", "Autumn", "Ava", "Avery", "Bailey", "Beatrice",
        "Bella", "Bethany", "Blair", "Bonnie", "Brianna", "Bridget", "Brooklyn", "Camila", "Carla", "Carmen",
        "Caroline", "Cassidy", "Catherine", "Cecilia", "Celeste", "Charlotte", "Chloe", "Christina", "Claire", "Clara",
        "Clementine", "Cora", "Daisy", "Dakota", "Dana", "Daphne", "Delilah", "Diana", "Eden", "Eleanor",
        "Elena", "Eliana", "Elise", "Elizabeth", "Ella", "Ellie", "Eloise", "Elsa", "Emery", "Emilia",
        "Emily", "Emma", "Erica", "Erin", "Eva", "Evelyn", "Faith", "Fiona", "Florence", "Francesca",
        "Freya", "Gabriella", "Gemma", "Georgia", "Gianna", "Gracie", "Grace", "Gwendolyn", "Hadley", "Hailey",
        "Hannah", "Harper", "Hazel", "Heidi", "Helen", "Holly", "Hope", "Imogen", "Iris", "Isabella",
        "Ivy", "Jade", "Jane", "Jasmine", "Josephine", "Joy", "Julia", "Juliana", "June", "Kaitlyn",
        "Kate", "Katherine", "Kayla", "Keira", "Kennedy", "Kiara", "Kinsley", "Layla", "Leah", "Leila",
        "Lena", "Lila", "Lilian", "Lillian", "Lily", "Linda", "Lola", "London", "Luciana", "Lucy",
        "Luna", "Lydia", "Mackenzie", "Maddison", "Madeline", "Madison", "Maeve", "Maggie", "Maya", "Margaret",
        "Maria", "Mariana", "Marley", "Martha", "Mary", "Matilda", "Mckenzie", "Megan", "Melanie", "Melody",
        "Mia", "Mila", "Molly", "Morgan", "Nadia", "Naomi", "Natalie", "Nevaeh", "Nicole", "Nora",
        "Oakley", "Olive", "Olivia", "Paige", "Paisley", "Parker", "Patricia", "Paula", "Pearl", "Penelope",
        "Phoebe", "Piper", "Poppy", "Quinn", "Rachel", "Reagan", "Rebecca", "Reese", "Riley", "River",
        "Rosa", "Rose", "Rosalie", "Ruby", "Ruth", "Sadie", "Sage", "Samantha", "Sara", "Sarah",
        "Savannah", "Scarlett", "Serenity", "Sienna", "Skylar", "Sofia", "Sophia", "Stella", "Summer", "Sydney",
        "Taylor", "Teagan", "Tessa", "Thea", "Theresa", "Tiffany", "Valentina", "Valerie", "Vanessa", "Vera",
        "Victoria", "Violet", "Vivian", "Willow", "Winter", "Zara", "Zoe", "Zoey", "Aaliyah", "Adalyn",
        "Adriana", "Alana", "Alexa", "Alexandra", "Alexis", "Alina", "Alison", "Allison", "Alyssa", "Amara",
        "Amber", "Amira", "Amy", "Anabelle", "Andrea", "Angelina", "Aniyah", "Annabel", "Anne", "Antonella",
        "Arabella", "Arianna", "Ariel", "Aspen", "Athena", "Aubrey", "Aurora", "Ayla", "Brielle", "Brynn",
        "Cadence", "Caitlin", "Callie", "Camille", "Carly", "Carolina", "Casey", "Cassandra", "Catalina", "Cecily",
        "Celestine", "Charity", "Chelsea", "Cheyenne", "Colette", "Crystal", "Dahlia", "Danielle", "Daphne", "Delaney",
        "Destiny", "Diana", "Dominique", "Eden", "Eileen", "Elaina", "Elisa", "Elodie", "Elowen", "Emery",
        "Emerson", "Esme", "Esther", "Evangeline", "Everly", "Fallon", "Faye", "Felicity", "Fern", "Finley",
        "Frida", "Genevieve", "Giselle", "Gloria", "Greta", "Guinevere", "Gwen", "Hadley", "Harlow", "Harley",
        "Harmony", "Harriet", "Haven", "Hayley", "Holland", "Honor", "Isla", "Jacqueline", "Jade", "Jana",
        "Janet", "Janice", "Jenna", "Jennifer", "Jessica", "Jillian", "Joanna", "Jocelyn", "Jolene", "Jordan",
        "Josie", "Joyce", "Judith", "Juliet", "Juliette", "Kara", "Karen", "Karla", "Katelyn", "Kendall",
        "Kendra", "Kennedy", "Kimberly", "Kira", "Kyla", "Kylee", "Lacey", "Lana", "Laura", "Lauren",
        "Lena", "Leilani", "Lennon", "Lexi", "Leyla", "Liliana", "Lilly", "Lindsay", "Lindsey", "Lisa",
        "Liv", "Londyn", "Lorelei", "Lorraine", "Louise", "Lucille", "Luna", "Lyric", "Mabel", "Maci",
        "Mackenna", "Macy", "Maddox", "Mae", "Maisie", "Mallory", "Maren", "Margot", "Marley", "Mckenna",
        "Mckenzie", "McKenzie", "Meadow", "Meredith", "Mia", "Michaela", "Michelle", "Millie", "Miranda", "Molly",
        "Monica", "Monroe", "Morgan", "Myra", "Nadia", "Nala", "Nancy", "Natalia", "Natasha", "Niamh",
        "Nichole", "Nina", "Noelle", "Nola", "Nyla", "Octavia", "Ophelia", "Paloma", "Pandora", "Paris",
        "Payton", "Penny", "Presley", "Primrose", "Quinn", "Raegan", "Raven", "Reagan", "Reign", "Remi",
        "Remy", "Renee", "Reyna", "Rhea", "Riley", "Romilly", "Rory", "Rosalind", "Rosemary", "Rowan",
        "Roxanne", "Rylee", "Rylie", "Sadie", "Sage", "Sally", "Sandra", "Sawyer", "Selena", "Serena",
        "Shiloh", "Sierra", "Simone", "Sloane", "Sonia", "Sophie", "Stevie", "Sutton", "Sylvie", "Tabitha",
        "Talia", "Tatum", "Tatum", "Taya", "Tessa", "Thalia", "Theodora", "Tiana", "Tiffany", "Tinsley",
        "Tori", "Trinity", "Vada", "Valeria", "Vera", "Veronica", "Vienna", "Viola", "Wren", "Wynter",
        "Ximena", "Yara", "Yasmine", "Zelda", "Zuri", "Ainsley", "Alaina", "Alayna", "Alivia", "Alondra",
        "Amaia", "Amalia", "Amaya", "Amelie", "Amirah", "Anaya", "Anika", "Annalise", "Annika", "Anya",
        "Arden", "Ariella", "Arlette", "Arwen", "Ashton", "Astrid", "Athalia", "Aubrie", "Audra", "Aurelia",
        "Austyn", "Aviana", "Avril", "Azalea", "Baylor", "Belle", "Berkley", "Bexley", "Blakely", "Blaire",
        "Blythe", "Bria", "Briar", "Bridgette", "Brinley", "Bristol", "Brittany", "Bronwyn", "Brylee", "Cali",
        "Calliope", "Cambria", "Camryn", "Carter", "Carys", "Celine", "Charlee", "Charley", "Charli", "Collins",
        "Coraline", "Cordelia", "Cove", "Dakota", "Dallas", "Demi", "Demi", "Demi", "Drew", "Eira",
        "Elara", "Eleni", "Eliora", "Ellis", "Ellison", "Ember", "Emersyn", "Emory", "Ensley", "Etta",
        "Evalyn", "Evie", "Farrah", "Faye", "Felicity", "Frankie", "Gracelyn", "Gracelynn", "Gracen", "Greer",
        "Grier", "Haisley", "Halle", "Hana", "Hanna", "Harlow", "Hattie", "Haven", "Holland", "Hollis",
        "Holland", "Hunter", "Indie", "Indigo", "Irene", "Isabel", "Isabela", "Isla", "Itzel", "Jade",
        "Jaliyah", "Jamie", "Janae", "Janelle", "Janiyah", "Jemma", "Jenna", "Jerzee", "Jolie", "Jordyn",
        "Journey", "Joy", "Jules", "Juliet", "Kailani", "Kaisley", "Kali", "Kallie", "Kamila", "Kamryn",
        "Karsyn", "Kassidy", "Katalina", "Katelynn", "Kaylee", "Kayleigh", "Kelsey", "Kendall", "Kenley", "Kenna",
        "Kensley", "Kiera", "Kira", "Kyla", "Kynlee", "Lainey", "Lakelyn", "Laney", "Lara", "Larkin",
        "Lennox", "Lea", "Leia", "Lennon", "Lennox", "Lexie", "Liana", "Liberty", "Lila", "Lilith",
        "Lilly", "Lina", "Livia", "Logan", "Londyn", "Lorelai", "Lottie", "Luciana", "Lucia", "Luna",
        "Lyra", "Maci", "Mackenzie", "Macy", "Madelyn", "Madilyn", "Maeve", "Magnolia", "Makenna", "Makenzie",
        "Malani", "Malaya", "Maliah", "Mallory", "Mariana", "Marlee", "Marleigh", "Marley", "Mckenna", "Mckenzie",
        "Mckenna", "Meadow", "Mckenzie", "Melany", "Melina", "Melissa", "Mercy", "Mila", "Milan", "Millie",
        "Mira", "Mirabel", "Mckenna", "Molly", "Monroe", "Morgan", "Mya", "Myla", "Nala", "Naya",
        "Nevaeh", "Nia", "Nola", "Noa", "Nola", "Noor", "Nyla", "Oakley", "Oaklyn", "Oaklynn",
        "Octavia", "Olive", "Opal", "Paloma", "Parker", "Peyton", "Phoenix", "Pippa", "Presley", "Queen",
        "Raelyn", "Raelynn", "Raegan", "Reese", "Regina", "Reign", "Remington", "Reyna", "Riley", "Ripley",
        "Rivka", "Romina", "Rory", "Rosalie", "Rosalie", "Rosie", "Royal", "Royalty", "Ryleigh", "Saanvi",
        "Sadie", "Sage", "Sariah", "Saylor", "Scarlet", "Selah", "Saylor", "Shay", "Shelby", "Siena",
        "Sierra", "Simone", "Skye", "Sloan", "Sloane", "Soleil", "Sophia", "Stevie", "Sutton", "Sylvia",
        "Talia", "Tatiana", "Tenley", "Tessa", "Tinsley", "Tori", "Treasure", "True", "Tyra", "Valery",
        "Vada", "Valentina", "Vera", "Verity", "Vida", "Vivian", "Waverly", "Willa", "Willow", "Winnie",
        "Wrenley", "Wynne", "Xena", "Yaretzi", "Zariah", "Zaylee", "Zelda", "Zhavia", "Zola", "Zora"
    );

    public static String pickRandom(RandomSource random) {
        return NAMES.get(random.nextInt(NAMES.size()));
    }
}
