package com.beckytidus.girlfriendmod.dialogue;

import com.beckytidus.girlfriendmod.entity.GirlFriendEntity;

public final class HugAndHitResponses {
    private static final String[] HUG = new String[]{
        "*hugs you back* I needed that.",
        "*kisses your cheek* You're so sweet to me.",
        "Mhm, that feels nice...",
        "I love when you pay attention to me.",
        "You always know how to make me feel better.",
        "Your touch means everything to me.",
        "I feel so safe with you.",
        "I was just thinking about you.",
        "We've been through so much together.",
        "You're my favorite person in this world.",
        "I trust you with my life.",
        "Hey... thanks for being here.",
        "I'm glad you're my partner.",
        "Sometimes I just need to hear your voice.",
        "You make this adventure worth it.",
        "Oh, hi...",
        "I'm still getting to know you.",
        "We'll grow closer, right?",
        "I want to understand you better.",
        "*squeezes you tight* Don't let go.",
        "You're so warm. I could stay here forever.",
        "This is exactly what I needed.",
        "You have no idea how much this means to me.",
        "*nuzzles* My hero.",
        "I'm so lucky you're mine.",
        "Hold me a little longer?",
        "Your arms are my favorite place.",
        "I could get used to this.",
        "You always know when I need a hug.",
        "Thank you for being here.",
        "I feel so loved right now.",
        "*hugs back* Never leave.",
        "You make everything better.",
        "I needed this so much.",
        "Stay with me?",
        "You're my safe place.",
        "I love you so much.",
        "This is perfect.",
        "You're the best thing in my life.",
        "Don't ever let me go.",
        "I'll never get tired of this.",
        "You're so good to me.",
        "My heart is so full right now.",
        "I'm so happy you're here.",
        "You always know how to make me smile.",
        "I could stay like this all day.",
        "You're my everything.",
        "Thank you for choosing me.",
        "I feel so close to you right now.",
        "You're my home.",
        "*holds you close* I've got you.",
        "You're so precious to me.",
        "I never want this moment to end.",
        "You make me feel so special.",
        "I'm so grateful for you.",
        "This is everything I wanted.",
        "You're my dream come true.",
        "I love being in your arms.",
        "You're so comforting.",
        "I feel so at peace with you.",
        "You're my person.",
        "Thank you for holding me.",
        "I needed to feel you close.",
        "You're the only one I want.",
        "I'm so glad we're together.",
        "You make me feel so loved.",
        "I could hug you forever.",
        "You're my safe haven.",
        "I feel so connected to you.",
        "You're my happy place.",
        "Thank you for being you.",
        "I love this so much.",
        "You're my comfort.",
        "I never feel alone with you.",
        "You're my peace.",
        "I'm so blessed to have you.",
        "You make every moment special.",
        "I feel so cherished.",
        "You're my heart.",
        "*tight hug* I'm not letting go.",
        "You're my sunshine.",
        "I love you more every day.",
        "You're my anchor.",
        "I feel so secure with you.",
        "You're my joy.",
        "Thank you for this moment.",
        "I'm so in love with you.",
        "You're my forever.",
        "I could never get enough of you.",
        "You're my treasure.",
        "I feel so complete with you.",
        "You're my soulmate.",
        "I love being yours.",
        "You're my miracle.",
        "I'm so lucky to be held by you.",
        "You're my paradise.",
        "I feel so blessed.",
        "You're my dream.",
        "Thank you for loving me.",
        "I'm so happy in your arms.",
        "You're my world.",
        "I love every second with you.",
        "You're my angel.",
        "I feel so alive with you.",
        "You're my destiny.",
        "I'm so grateful for this hug.",
        "You're my one and only.",
        "I love you to the moon and back.",
        "You're my perfect fit.",
        "I feel so warm inside.",
        "You're my happiness.",
        "I'm so at home with you.",
        "You're my everything and more.",
        "I love this feeling.",
        "You're my comfort zone.",
        "I feel so lucky.",
        "You're my heart's desire.",
        "I'm so in love.",
        "You're my forever and always.",
        "I love being close to you.",
        "You're my safe space.",
        "I feel so loved and wanted.",
        "You're my reason to smile.",
        "I'm so thankful for you.",
        "You're my beautiful person.",
        "I love you endlessly.",
        "You're my precious one.",
        "I feel so grateful.",
        "You're my darling.",
        "I'm so glad you're mine.",
    };

    private static final String[] HIT_BY_OWNER = new String[]{
        "I will fight back!",
        "Ouch! Why are you hurting me?",
        "Stop! What did I do?",
        "Why would you do that?",
        "That really hurt!",
        "I thought you loved me!",
        "Please don't hit me!",
        "I can't believe you did that!",
        "You're supposed to protect me!",
        "Why are you attacking me?",
        "That wasn't okay!",
        "I'm going to defend myself!",
        "How could you?",
        "I trusted you!",
        "Don't make me fight you!",
        "You're hurting me!",
        "I didn't deserve that!",
        "Stop it right now!",
        "I thought we were a team!",
        "This isn't like you!",
        "You're scaring me!",
        "I won't just take this!",
        "What's wrong with you?",
        "I loved you!",
        "Back off!",
        "I'm fighting back!",
        "You've crossed a line!",
        "I can't let this slide!",
        "That really stung!",
        "You're going to regret that!",
        "I'm not your punching bag!",
        "How dare you!",
        "I trusted you with my heart!",
        "You've lost my trust!",
        "I'll defend myself!",
        "That was cruel!",
        "I didn't expect this from you!",
        "You're supposed to be my partner!",
        "I'm disappointed in you!",
        "Don't push me!",
        "I'll fight back if I have to!",
        "You're being mean!",
        "I thought you cared!",
        "That hurt more than you know!",
        "I'm not going to take this!",
        "You've changed!",
        "I deserve better!",
        "Stop hurting me!",
        "I'll make you regret that!",
        "You broke my heart!",
        "I can't believe you'd do this!",
        "That's it, I'm fighting back!",
        "You've made a big mistake!",
        "I trusted you completely!",
        "Why would you hurt someone who loves you?",
        "I'm done being nice!",
        "You're going to pay for that!",
        "I thought we had something special!",
        "Don't test me!",
        "I'll show you what I'm made of!",
        "You've really upset me!",
        "I didn't sign up for this!",
        "You're acting like a monster!",
        "I'll remember this!",
        "That was so wrong!",
        "I'm not your enemy!",
        "You're making a huge mistake!",
        "I cared about you!",
        "Don't make me hurt you back!",
        "You've betrayed my trust!",
        "I'm going to defend myself now!",
        "That really wasn't okay!",
        "You're supposed to love me!",
        "I'm fighting back whether you like it or not!",
        "You've crossed the line!",
        "I won't forget this!",
        "That hurt so much!",
        "You're being really cruel!",
        "I thought you were different!",
        "Don't do that again!",
        "I'll make you sorry!",
        "You've lost me!",
        "I'm not going to stand for this!",
        "That was uncalled for!",
        "You're supposed to be on my side!",
        "I'm done with this!",
        "You've really hurt me!",
        "I'll get you back for that!",
        "You're not the person I thought you were!",
        "Don't push your luck!",
        "I'm going to fight back!",
        "You've made me angry!",
        "That was so unfair!",
        "I trusted you with everything!",
        "You're going to regret hurting me!",
        "I'm not just going to take it!",
        "You've broken something between us!",
        "Don't expect me to just forgive that!",
        "I'll defend myself to the end!",
        "You're being horrible!",
        "I thought you were my protector!",
        "That really shocked me!",
        "You've awakened my fighting spirit!",
        "I'm not helpless!",
        "You've made an enemy today!",
        "Don't think I won't fight back!",
        "I'm going to make you stop!",
        "You've hurt me deeply!",
        "I'll show you not to mess with me!",
        "You're supposed to cherish me!",
        "That was a terrible thing to do!",
        "I'm not going to take this lying down!",
        "You've shattered my trust!",
        "Don't underestimate me!",
        "I'm fighting for myself now!",
        "You've proven you're not who I thought!",
        "I'll make you think twice next time!",
        "You're being really unfair!",
        "I thought we were in this together!",
        "That was completely wrong!",
        "You've pushed me too far!",
        "I'm not your target!",
        "Don't make me do this!",
        "I'll stand my ground!",
        "You've really let me down!",
        "I'm going to retaliate!",
        "You're supposed to be kind to me!",
        "That hurt more than any weapon!",
        "I'm not going to just stand here!",
        "You've shown your true colors!",
        "Don't expect me to take it!",
        "I'll fight with everything I have!",
        "You've wounded me!",
        "I'm done being passive!",
        "You're going to learn a lesson!",
        "That was so unnecessary!",
        "You've made me see you differently!",
        "I'm not defenseless!",
        "Don't try that again!",
        "I'll protect myself!",
        "You've really angered me!",
    };

    private static final String[] HIT_BY_OTHER = new String[]{
        "I'll fight back!",
        "Ouch! Why are you hurting me?",
        "Stay back!",
        "I won't let you hurt us!",
        "You're going to regret that!",
        "I'll protect my partner!",
        "Back off!",
        "I'm not going down without a fight!",
        "You've made a mistake!",
        "I'll defend myself!",
        "Don't mess with me!",
        "I'm stronger than I look!",
        "You're in for it now!",
        "I won't stand for this!",
        "Prepare yourself!",
        "I'll show you!",
        "You've picked the wrong fight!",
        "I'm fighting back!",
        "Don't touch me!",
        "I'll make you pay!",
        "You're going to get it!",
        "I'm not an easy target!",
        "You've angered me!",
        "I'll protect what's mine!",
        "Back away!",
        "I'm ready for you!",
        "You've crossed the line!",
        "I won't take this!",
        "Prepare to fight!",
        "I'll defend my owner!",
        "Don't underestimate me!",
        "I'm coming for you!",
        "You've made an enemy!",
        "I'll fight to the end!",
        "Stay away from us!",
        "I'm not scared of you!",
        "You're going down!",
        "I'll show you what I've got!",
        "Don't test me!",
        "I'm not going to run!",
        "You've started something!",
        "I'll stand my ground!",
        "Get back!",
        "I'm ready to fight!",
        "You've chosen the wrong person!",
        "I won't back down!",
        "Prepare yourself for a fight!",
        "I'll make you regret that!",
        "Don't push me!",
        "I'm fighting for us!",
        "You've messed with the wrong couple!",
        "I'll protect us!",
        "Stay off!",
        "I'm not helpless!",
        "You're going to regret this!",
        "I'll give you a fight!",
        "Don't come any closer!",
        "I'm defending myself!",
        "You've awakened my fury!",
        "I won't let you win!",
        "Back off now!",
        "I'm stronger than you think!",
        "You've made a big mistake!",
        "I'll fight with everything I have!",
        "Don't make me hurt you!",
        "I'm not going to take this!",
        "You've attacked the wrong one!",
        "I'll stand up to you!",
        "Get away from me!",
        "I'm ready!",
        "You've started a fight you can't win!",
        "I won't give up!",
        "Prepare to be defeated!",
        "I'll defend to the last!",
        "Don't underestimate us!",
        "I'm coming at you!",
        "You've made me angry!",
        "I'll fight back with everything!",
        "Stay back or else!",
        "I'm not running!",
        "You're going to get a taste of your own medicine!",
        "I'll show you my strength!",
        "Don't try it!",
        "I'm protecting what I love!",
        "You've chosen to fight!",
        "I won't be pushed around!",
        "Back away now!",
        "I'm not afraid of you!",
        "You've picked a fight!",
        "I'll make you back off!",
        "Don't threaten us!",
        "I'm standing my ground!",
        "You've attacked us!",
        "I won't let you hurt him!",
        "Prepare for battle!",
        "I'll fight to protect!",
        "Don't mess with us!",
        "I'm not going to fall!",
        "You've made a fatal error!",
        "I'll retaliate!",
        "Stay away!",
        "I'm ready to defend!",
        "You've crossed me!",
        "I won't surrender!",
        "Back off or face the consequences!",
        "I'm not easy prey!",
        "You've angered the wrong person!",
        "I'll fight with all my might!",
        "Don't touch us!",
        "I'm defending my partner!",
        "You've started a war!",
        "I won't go down!",
        "Prepare yourself!",
        "I'll show you no mercy!",
        "Don't come near us!",
        "I'm fighting for our safety!",
        "You've made a grave mistake!",
        "I'll make you regret attacking us!",
        "Stay back, I'm warning you!",
        "I'm not going to take this lying down!",
        "You've chosen the wrong target!",
        "I won't let you get away with this!",
        "Back away from my partner!",
        "I'm not defenseless!",
        "You've provoked me!",
        "I'll fight until the end!",
        "Don't test my patience!",
        "I'm protecting my love!",
        "You've declared war!",
        "I won't stand by!",
        "Prepare for my wrath!",
        "I'll defend with my life!",
        "Don't make me do this!",
        "I'm not backing down!",
        "You've attacked the one I love!",
        "I'll fight to the death if I have to!",
        "Stay away from him!",
        "I'm ready to fight back!",
        "You've made an enemy for life!",
        "I won't let you hurt me again!",
    };

    public static String pickHug(GirlFriendEntity gf) {
        return HUG[gf.getEntityWorld().getRandom().nextInt(HUG.length)];
    }

    public static String pickHitByOwner(GirlFriendEntity gf) {
        return HIT_BY_OWNER[gf.getEntityWorld().getRandom().nextInt(HIT_BY_OWNER.length)];
    }

    public static String pickHitByOther(GirlFriendEntity gf) {
        return HIT_BY_OTHER[gf.getEntityWorld().getRandom().nextInt(HIT_BY_OTHER.length)];
    }
}
