package com.beckytidus.girlfriendmod.dialogue;

import com.beckytidus.girlfriendmod.entity.GirlFriendEntity;
import net.minecraft.world.World;

public final class WaitAndFollowLines {
    private static final String[] WAIT_HERE = new String[]{
        "I'll wait here for you.",
        "I'll stay right here until you're back.",
        "Take your time. I'm not going anywhere.",
        "I'll be here when you return.",
        "I'll hold down the fort.",
        "I'll wait right here. Come back soon.",
        "Don't worry, I'll stay put.",
        "I'll be waiting here for you.",
        "I'll keep this spot warm for you.",
        "Go ahead. I'll wait.",
        "I'll stay here and wait for you.",
        "I'm not moving. I'll be right here.",
        "I'll wait here. Hurry back.",
        "I'll be right here when you need me.",
        "Take care. I'll wait here.",
        "I'll stay behind. Come find me when you're done.",
        "I'll wait here. Don't forget me.",
        "I'll be here, same spot.",
        "I'll wait. Come back safe.",
        "I'll hold the line here.",
        "I'll stay and wait. You go ahead.",
        "I'll wait right here for when you return.",
        "I'm staying put. See you soon.",
        "I'll be waiting. Don't be long.",
        "I'll wait here. Come back to me.",
        "I'll stay here. Be careful out there.",
        "I'll wait. I'm not going anywhere.",
        "I'll be right here. Go do your thing.",
        "I'll wait here. I promise.",
        "I'll stay and keep watch here.",
        "I'll wait for you here. Always.",
        "I'll be here. Come back soon.",
        "I'll stay right here. Hurry back.",
        "I'll wait. I've got nothing but time.",
        "I'll be waiting here. Stay safe.",
        "I'll hold still here for you.",
        "I'll wait here. Don't keep me waiting too long.",
        "I'll stay put. Return when you're ready.",
        "I'll be right here waiting.",
        "I'll wait here. I'll be fine.",
        "I'll stay. Come back to me soon.",
        "I'll wait. I'm patient.",
        "I'll be here. Go on.",
        "I'll wait right here. Miss you already.",
        "I'll stay here. Bring back something nice.",
        "I'll wait. I believe in you.",
        "I'll be waiting. Come back in one piece.",
        "I'll stay and wait. Good luck.",
        "I'll wait here. You're worth waiting for.",
        "I'll be right here. Take your time.",
        "I'll wait. I'll count the seconds.",
        "I'll stay put. See you when you get back.",
        "I'll wait here. Don't worry about me.",
        "I'll be here when you return. Promise.",
        "I'll wait. Come back soon, okay?",
        "I'll stay right here. I'm not leaving.",
        "I'll wait here. Be safe.",
        "I'll be waiting. Hurry back to me.",
        "I'll stay. I'll be thinking of you.",
        "I'll wait. You're the one I'm waiting for.",
        "I'll be right here. Go get 'em.",
        "I'll wait here. Come back with stories.",
        "I'll stay and wait. I trust you.",
        "I'll wait. My heart stays with you.",
        "I'll be here. Come back to your girl.",
        "I'll wait right here. Don't forget to return.",
        "I'll stay put. I'll miss you.",
        "I'll wait here. Return safely.",
        "I'll be waiting here. You mean everything.",
        "I'll wait. I'll be right here.",
        "I'll stay. Come back soon, love.",
        "I'll wait here. I've got your back from here.",
        "I'll be right here. Go explore.",
        "I'll wait. I'll be the one waiting.",
        "I'll stay here. Come find me later.",
        "I'll wait here. Take all the time you need.",
        "I'll be here. I'm not going anywhere.",
        "I'll wait. Stay focused out there.",
        "I'll stay right here. Come back when you're done.",
        "I'll wait here. I'll be okay.",
        "I'll be waiting. You're worth it.",
        "I'll wait. See you soon.",
        "I'll stay. Don't rush for me.",
        "I'll wait here. I'll be right here.",
        "I'll be right here. Come back to me.",
        "I'll wait. I'll hold the fort.",
        "I'll stay here. Return when you can.",
        "I'll wait here. I believe you'll come back.",
        "I'll be waiting here. Go.",
        "I'll wait. I'm staying.",
        "I'll stay put. I'll be here.",
        "I'll wait right here. Don't be gone long.",
        "I'll be here. Wait for you? Always.",
        "I'll wait. I've got nowhere else to be.",
        "I'll stay. You're my reason to wait.",
        "I'll wait here. Come back in one piece.",
        "I'll be right here waiting. Promise.",
        "I'll wait. I'll be fine right here.",
        "I'll stay here. Hurry back, okay?",
        "I'll wait. I'm not moving an inch.",
        "I'll be waiting. Same spot, same me.",
        "I'll wait here. Take care of yourself.",
        "I'll stay. I'll be here when you're back.",
        "I'll wait. Go. I'll be here.",
        "I'll be here. Waiting. Always.",
        "I'll wait right here. Miss you.",
        "I'll stay put. Come back safe.",
        "I'll wait here. You're my home.",
        "I'll be waiting. Don't forget to come back.",
        "I'll wait. I'll stay. I'll be here.",
        "I'll stay here. See you soon.",
        "I'll wait. My place is right here.",
        "I'll be right here. Go do what you need.",
        "I'll wait here. I'm not going anywhere.",
        "I'll stay. I'll wait. For you.",
        "I'll wait. Come back to this spot.",
        "I'll be here. Waiting for you.",
        "I'll wait right here. Return to me.",
        "I'll stay. I'll be right here.",
        "I'll wait here. Be careful.",
        "I'll be waiting. I'll be here.",
        "I'll wait. Stay safe out there.",
        "I'll stay here. I'll wait for you.",
        "I'll wait. You'll find me here.",
        "I'll be right here. Same place.",
        "I'll wait here. Don't worry.",
        "I'll stay put. I'll wait.",
        "I'll wait. I'm right here.",
        "I'll be here. Not moving.",
        "I'll wait right here. Come back.",
        "I'll stay. Here. Waiting.",
        "I'll wait here. For you. Always.",
    };

    private static final String[] FOLLOW_YOU = new String[]{
        "I'm following you!",
        "I'll follow you anywhere.",
        "Lead the way. I'm right behind you.",
        "I'm with you. Let's go.",
        "I'll follow you. Don't leave me behind.",
        "I'm coming with you!",
        "I'll stick with you.",
        "I'm right behind you.",
        "I'll follow. You're not getting rid of me.",
        "I'm following. Where you go, I go.",
        "I'll follow you. Let's do this.",
        "I'm with you all the way.",
        "I'll follow. Lead on.",
        "I'm coming. Don't go too fast.",
        "I'll follow you anywhere you go.",
        "I'm right behind you. Let's go.",
        "I'll stick by your side.",
        "I'm following. You're my leader.",
        "I'll follow. I've got your back.",
        "I'm with you. Where to?",
        "I'll follow you. Together.",
        "I'm coming with. Don't leave me.",
        "I'll follow. I'm not staying behind.",
        "I'm right behind you. Ready.",
        "I'll follow you. Let's move.",
        "I'm with you. Lead the way.",
        "I'll follow. You're not alone.",
        "I'm following. Count me in.",
        "I'll follow you. My place is with you.",
        "I'm coming. I'm right here.",
        "I'll stick with you. Always.",
        "I'm following you. Let's go.",
        "I'll follow. You're my person.",
        "I'm with you. I'll follow.",
        "I'll follow you. No question.",
        "I'm right behind you. Go.",
        "I'll follow. Where we go, we go together.",
        "I'm coming with you. Don't run off.",
        "I'll follow you. I'm in.",
        "I'm following. You lead, I follow.",
        "I'll stick by you. Let's go.",
        "I'm with you. Following.",
        "I'll follow. I'm not letting you go alone.",
        "I'm right behind you. I'm here.",
        "I'll follow you. Together we go.",
        "I'm following. You're stuck with me.",
        "I'll follow. My feet are moving.",
        "I'm coming. I'm following you.",
        "I'll follow you. Let's do this together.",
        "I'm with you. I'll follow anywhere.",
        "I'll follow. You're my everything.",
        "I'm right behind you. Don't worry.",
        "I'll follow you. I'm ready.",
        "I'm following. Let's go already.",
        "I'll stick with you. I'm coming.",
        "I'm with you. I'll be right there.",
        "I'll follow. Lead and I'll follow.",
        "I'm coming with. I'm following.",
        "I'll follow you. You're not alone.",
        "I'm right behind you. Let's move.",
        "I'll follow. I'm with you.",
        "I'm following you. Ready when you are.",
        "I'll follow you. My place is beside you.",
        "I'm with you. Following your lead.",
        "I'll follow. Don't leave without me.",
        "I'm coming. I'll follow you.",
        "I'll follow you. We're a team.",
        "I'm right behind you. I promise.",
        "I'll stick by your side. Let's go.",
        "I'm following. You're my partner.",
        "I'll follow. I'm right behind you.",
        "I'm with you. I'll follow you.",
        "I'll follow you. No way I'm staying.",
        "I'm coming with you. I'm here.",
        "I'll follow. You lead, I follow.",
        "I'm right behind you. Together.",
        "I'll follow you. Let's go together.",
        "I'm following. I'm not staying put.",
        "I'll follow. I'm coming with.",
        "I'm with you. Don't go without me.",
        "I'll follow you. I'm right here.",
        "I'm coming. I'll stick with you.",
        "I'll follow. Where you lead.",
        "I'm right behind you. I'm following.",
        "I'll follow you. You're my guide.",
        "I'm following you. Let's move.",
        "I'll stick with you. I'm in.",
        "I'm with you. I'll follow.",
        "I'll follow. I'm right behind you.",
        "I'm coming with. Following you.",
        "I'll follow you. Together we're stronger.",
        "I'm right behind you. Lead on.",
        "I'll follow. I'm with you all the way.",
        "I'm following. You're not going alone.",
        "I'll follow you. I'm ready to go.",
        "I'm with you. I'm following.",
        "I'll follow. Let's go. I'm right behind you.",
        "I'm coming. I'll follow you anywhere.",
        "I'll follow you. I'm here.",
        "I'm right behind you. Let's do this.",
        "I'll stick by you. I'm following.",
        "I'm following you. You're stuck with me.",
        "I'll follow. I'm coming with you.",
        "I'm with you. Right behind you.",
        "I'll follow you. Don't leave me.",
        "I'm coming with you. I'm following.",
        "I'll follow. I'm not staying.",
        "I'm right behind you. I'm with you.",
        "I'll follow you. We go together.",
        "I'm following. I'm right here.",
        "I'll follow. You're my leader.",
        "I'm with you. I'll stick with you.",
        "I'll follow you. Lead the way.",
        "I'm coming. I'm right behind you.",
        "I'll follow. I'm with you.",
        "I'm right behind you. I'll follow.",
        "I'll follow you. I'm coming.",
        "I'm following. Let's go. I'm ready.",
        "I'll stick with you. Following.",
        "I'm with you. I'll follow you.",
        "I'll follow you. I'm not leaving your side.",
        "I'm right behind you. Count me in.",
        "I'll follow. I'm coming with you.",
        "I'm following you. You're not alone.",
        "I'll follow you. I've got your back.",
        "I'm with you. I'm following you.",
        "I'll follow. Right behind you.",
        "I'm coming with. I'm right here.",
        "I'll follow you. Together.",
        "I'm right behind you. I'm here.",
        "I'll follow. I'm coming.",
        "I'm following. You're my person.",
        "I'll follow you. Let's go.",
        "I'm with you. I'll follow anywhere.",
        "I'll follow. I'm right there.",
        "I'm coming. I'll stick with you.",
        "I'll follow you. I'm in.",
        "I'm right behind you. Let's go.",
        "I'll follow. I'm with you.",
        "I'm following you. I'm coming.",
        "I'll follow you. Lead on.",
        "I'm with you. Right behind you.",
        "I'll follow. I'm not staying behind.",
        "I'm right behind you. I'm following.",
        "I'll follow you. I'm ready.",
        "I'm following. I'm with you.",
        "I'll follow. Let's move.",
        "I'm with you. I'm coming.",
        "I'll follow you. Don't go without me.",
    };

    public static String pickWaitHere(GirlFriendEntity gf) {
        World w = gf.getEntityWorld();
        return WAIT_HERE[w.getRandom().nextInt(WAIT_HERE.length)];
    }

    public static String pickFollowYou(GirlFriendEntity gf) {
        World w = gf.getEntityWorld();
        return FOLLOW_YOU[w.getRandom().nextInt(FOLLOW_YOU.length)];
    }
}
